<a href="https://colab.research.google.com/github/nursedakarabacak/house-price-prediction/blob/main/ev_fiyat_tahmini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dosya = '/content/drive/MyDrive/train.csv'
df= pd.read_csv(dosya)
df.head(3)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500

In [ ]:
#eksik verileri gormek icin
eksikler =df.isnull().sum()
eksikler[eksikler>0]

sayisal_sutunlar = df[eksikler.index].select_dtypes(include=['float64','int64']).columns
kategorik_sutunlar = df[eksikler.index].select_dtypes(include=['object']).columns

for sutun in sayisal_sutunlar:
  df[sutun] = df[sutun].fillna(df[sutun].median())

for sutun in kategorik_sutunlar:
    df[sutun] = df[sutun].fillna(df[sutun].mode()[0])

In [ ]:
df.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

In [ ]:
df = pd.get_dummies(df, columns=df.select_dtypes(include=["object"]).columns, dtype=int)

In [ ]:
df.select_dtypes(include=["object"]).columns

Index([], dtype='object')

In [ ]:
#x sorular ozellikler ,y cevap hedefler

y = df["SalePrice"]
x = df.drop("SalePrice", axis=1)

In [ ]:
x.shape

(1460, 288)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

print(x_train.shape)
print(x_test.shape)

(1168, 288)
(292, 288)

In [ ]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
#tahminler
y_pred = model.predict(x_test)
y_pred[:5]

array([149443.35641056, 188057.07522754, 142760.12440175, 163364.40433233,
        97140.61496402])

In [ ]:
#karsılastırma
print("tahmin", y_pred[:5])
print("gercek", y_test[:5])

tahmin [149443.35641056 188057.07522754 142760.12440175 163364.40433233
  97140.61496402]
gercek 717     157000
266     185000
1458    142125
265     175500
912      88000
Name: SalePrice, dtype: int64

In [ ]:
#mea(mean absolute errror): tahminler ortalamadan kaç dolar saptı
#r^2 model veriyi ne kadar iyi açıklıyor

mae = mean_absolute_error(y_test.values, y_pred)
r2 = r2_score(y_test.values, y_pred)

print("MAE:", mae)
print("R²:", r2)

MAE: 18892.242886849184
R²: 0.7347346715624878

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       ...
       'SaleType_ConLw', 'SaleType_New', 'SaleType_Oth', 'SaleType_WD',
       'SaleCondition_Abnorml', 'SaleCondition_AdjLand',
       'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal',
       'SaleCondition_Partial'],
      dtype='object', length=289)

In [ ]:
df["TotalSF"] = df["TotalBsmtSF"] + df["1stFlrSF"] + df["2ndFlrSF"]
df["HouseAge"] = 2026 - df["YearBuilt"]
df[["TotalSF","HouseAge"]].head()

   TotalSF  HouseAge
0     2566        23
1     2524        50
2     2706        25
3     2473       111
4     3343        26

In [ ]:
#yeniden x ve y olusturmalıyım
y = df["SalePrice"]
x = df.drop("SalePrice",axis=1)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
model = LinearRegression()
model.fit(x_train,y_train)
#tahmin yap
y_pred = model.predict(x_test)
#degerlendir
mae = mean_absolute_error(y_test.values, y_pred)
r2 = r2_score(y_test.values, y_pred)
print("MAE:", mae)
print("R²:", r2)

MAE: 18548.65218764843
R²: 0.7824678606427157

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
model_rf = RandomForestRegressor()
model_rf.fit(x_train, y_train)
y_pred_rf = model_rf.predict(x_test)

mae_rf = mean_absolute_error(y_test.values, y_pred_rf)
r2_rf = r2_score(y_test.values, y_pred_rf)

print("MAE:", mae_rf)
print("R²:", r2_rf)

MAE: 17206.74702054794
R²: 0.8785067282298047

In [58]:
!git init
!git add .
!git commit -m "first commit"
!git branch -M main
!git remote add origin https://github.com/nursedakarabacak/house-price-prediction
!git push -u origin main

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@07def5f454ee.(none)')
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/nursedakarabacak/house-price-prediction'

In [59]:
!git config --global user.name "Nurseda Karabacak"
!git config --global user.email "nurseda.karabacak@outlook.com"

In [60]:
!git init
!git config --global user.name "Nurseda Karabacak"
!git config --global user.email "nursedakarabacak@outlook.com"
!git add .
!git commit -m "first commit"
!git branch -M main
!git remote add origin https://github.com/nursedakarabacak/house-price-prediction.git
!git push -u origin main

Reinitialized existing Git repository in /content/.git/
[main (root-commit) 5eba387] first commit
 27 files changed, 52525 insertions(+)
 create mode 100644 .config/.last_opt_in_prompt.yaml
 create mode 100644 .config/.last_survey_prompt.yaml
 create mode 100644 .config/.last_update_check.json
 create mode 100644 .config/active_config
 create mode 100644 .config/config_sentinel
 create mode 100644 .config/configurations/config_default
 create mode 100644 .config/default_configs.db
 create mode 100644 .config/gce
 create mode 100644 .config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
 create mode 100644 .config/logs/2026.01.16/14.23.31.981136.log
 create mode 100644 .config/logs/2026.01.16/14.24.03.314209.log
 create mode 100644 .config/logs/2026.01.16/14.24.13.071214.log
 create mode 100644 .config/logs/2026.01.16/14.24.18.954466.log
 create mode 100644 .config/logs/2026.01.16/14.24.28.646070.log
 create mode 100644 .config/logs/2026.01.16/14.24.29.392089.log
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of Untitled0.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled0.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled3.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/ev_fiyat_tahmini.ipynb
 create mode 100644 drive/MyDrive/train.csv
 create mode 100755 sample_data/README.md
 create mode 100755 sample_data/anscombe.json
 create mode 100644 sample_data/california_housing_test.csv
 create mode 100644 sample_data/california_housing_train.csv
 create mode 100644 sample_data/mnist_test.csv
 create mode 100644 sample_data/mnist_train_small.csv
error: remote origin already exists.
fatal: could not read Username for 'https://github.com': No such device or address